[en]
  title = "Z Themes Documentation"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"
  
[ko]
  title = "Z Themes Documentation"
  languageName = "한국어"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/en"